import Header from '@/app/components/layout/header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/app/components/layout/sidebar'
import Footer from '@/app/components/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className='grid grid-cols-8 gap-6 px-9 py-6'>
          <Sidebar />
          <main className='col-span-7'>
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  )
}
